<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
	<FilesToIncludeForPublish>OnlyFilesToRunTheApp</FilesToIncludeForPublish>
  </PropertyGroup>
  <ItemGroup>
	<ExcludeFromPackageFolders Include="ARM;SQL;.azure" />
	<ExcludeFromPackageFiles Include="README.md;SECURITY.md;CONTRIBUTING.md;LICENSE;openapi_mcp.json;bin\WebApiConfig.cs;devShop.wpp.targets" />
  </ItemGroup>
</Project>
